# Generated by Django 5.0.6 on 2026-07-18 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام صرافی')),
                ('logo', models.ImageField(upload_to='exchanges/', verbose_name='لوگو')),
                ('fee', models.CharField(help_text='مثلاً: 0.1% یا رایگان برای ثبت\u200cنامی\u200cهای جدید', max_length=50, verbose_name='کارمزد')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, help_text='عدد اعشاری بین ۰ تا ۵ (مثلاً 4.5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (از ۵)')),
                ('short_description', models.CharField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('registration_url', models.URLField(verbose_name='لینک ثبت\u200cنام')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'صرافی',
                'verbose_name_plural': 'صرافی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
    ]
