# Generated by Django 4.2.26 on 2026-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='fee',
        ),
        migrations.AddField(
            model_name='exchange',
            name='maker_fee',
            field=models.CharField(default='', help_text='مثلاً: 0.1%', max_length=20, verbose_name='کارمزد میکر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='taker_fee',
            field=models.CharField(default='', help_text='مثلاً: 0.2%', max_length=20, verbose_name='کارمزد تیکر'),
            preserve_default=False,
        ),
    ]
