# Generated by Django 5.0.6 on 2026-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTC', 'بیت کوین'), ('ETH', 'اتریوم'), ('SOL', 'سولانا'), ('USDT', 'تتر'), ('GOLD18', 'طلای ۱۸ عیار')], max_length=10, unique=True, verbose_name='نماد')),
                ('name_fa', models.CharField(max_length=50, verbose_name='نام فارسی')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='قیمت')),
                ('currency', models.CharField(choices=[('USD', 'دلار'), ('IRR', 'ریال')], max_length=3, verbose_name='واحد پول')),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='درصد تغییر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت\u200cها',
                'ordering': ['symbol'],
            },
        ),
    ]
