# Generated by Django 5.0.6 on 2026-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='symbol',
            field=models.CharField(choices=[('BTC', 'بیت کوین'), ('ETH', 'اتریوم'), ('SOL', 'سولانا'), ('USD', 'دلار'), ('GOLD18', 'طلای ۱۸ عیار')], max_length=10, unique=True, verbose_name='نماد'),
        ),
    ]
