# Generated by Django 4.2.26 on 2026-08-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_price_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='symbol',
            field=models.CharField(choices=[('BTC', 'بیت کوین'), ('ETH', 'اتریوم'), ('SOL', 'سولانا'), ('BNB', 'بایننس کوین'), ('HYPE', 'هایپرلیکوئید'), ('XAUT', 'طلا (تتر گلد)'), ('USD', 'دلار'), ('GOLD18', 'طلای ۱۸ عیار')], max_length=10, unique=True, verbose_name='نماد'),
        ),
    ]
