# Generated by Django 5.0.6 on 2026-07-10 07:42

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=80, unique=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='نامک (Slug)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, help_text='در صورتی که این دسته\u200cبندی زیرمجموعه یک دسته\u200cبندی دیگر است انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.category', verbose_name='دسته\u200cبندی مادر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='تایتل مقاله')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=280, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/', verbose_name='تصویر مقاله')),
                ('summary', models.TextField(max_length=500, verbose_name='خلاصه مقاله')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن مقاله')),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, help_text='در صورت خالی گذاشتن، بصورت خودکار محاسبه می\u200cشود.', null=True, verbose_name='مدت زمان مطالعه (دقیقه)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='published', max_length=10, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.category', verbose_name='دسته\u200cبندی')),
                ('main_tags', models.ManyToManyField(blank=True, help_text='دقیقاً باید ۳ تگ اصلی برای هر مقاله انتخاب شود.', related_name='main_articles', to='articles.tag', verbose_name='سه تگ اصلی')),
                ('secondary_tags', models.ManyToManyField(blank=True, related_name='secondary_articles', to='articles.tag', verbose_name='تگ\u200cهای فرعی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
