# Generated by Django 5.0.6 on 2026-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_posted_to_telegram',
            field=models.BooleanField(default=False, editable=False, verbose_name='در تلگرام پست شده'),
        ),
    ]
