# Generated by Django 4.2.26 on 2026-07-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_posted_to_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='articles.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', 'id'],
            },
        ),
    ]
