# Generated by Django 5.0.6 on 2026-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان رویداد')),
                ('country', models.CharField(help_text='مثلاً USD، EUR', max_length=10, verbose_name='کشور/ارز')),
                ('importance', models.CharField(choices=[('high', 'بسیار مهم (قرمز)'), ('medium', 'مهم (نارنجی)'), ('low', 'کم\u200cاهمیت (زرد)')], max_length=10, verbose_name='اهمیت')),
                ('event_date', models.DateField(verbose_name='تاریخ (میلادی)')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='ساعت')),
                ('actual', models.CharField(blank=True, max_length=30, verbose_name='مقدار واقعی')),
                ('forecast', models.CharField(blank=True, max_length=30, verbose_name='پیش\u200cبینی')),
                ('previous', models.CharField(blank=True, max_length=30, verbose_name='مقدار قبلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد اقتصادی',
                'verbose_name_plural': 'رویدادهای اقتصادی',
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
