# Generated by Django 4.2.26 on 2026-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('link_url', models.URLField(verbose_name='لینک مقصد (وقتی کاربر روی بنر کلیک کند)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر بالای سایت',
                'verbose_name_plural': 'بنرهای بالای سایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
