# Generated by Django 4.2.26 on 2026-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners/mobile/', verbose_name='تصویر بنر (موبایل - اختیاری)'),
        ),
    ]
