# Generated by Django 4.2.26 on 2026-09-19 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topbanner', '0002_topbanner_image_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='alt_text',
            field=models.CharField(blank=True, help_text='توضیح کوتاه محتوای بنر؛ برای سئو و کاربران اسکرین\u200cریدر. مثال: «جشنواره ثبت\u200cنام صرافی نوبیتکس».', max_length=125, verbose_name='متن جایگزین تصویر (alt)'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='background_color',
            field=models.CharField(default='#111318', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='desktop_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='desktop_jpeg',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='banners/generated/'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='desktop_webp',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='banners/generated/'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='desktop_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='display_height_desktop',
            field=models.PositiveSmallIntegerField(default=92, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(220)], verbose_name='ارتفاع نوار در دسکتاپ (پیکسل)'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='display_height_mobile',
            field=models.PositiveSmallIntegerField(default=104, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(260)], verbose_name='ارتفاع نوار در موبایل (پیکسل)'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='fit_mode',
            field=models.CharField(choices=[('cover', 'پر کردن کامل نوار (ممکن است کمی از لبه\u200cها بریده شود)'), ('contain', 'نمایش کل بنر بدون برش (دو طرف با رنگ بنر پر می\u200cشود)')], default='cover', max_length=10, verbose_name='نحوه جا شدن تصویر'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='focus',
            field=models.CharField(choices=[('center', 'وسط'), ('right', 'راست'), ('left', 'چپ')], default='center', help_text='وقتی حالت «پر کردن کامل» انتخاب شده، این قسمت از تصویر حتماً حفظ می\u200cشود.', max_length=10, verbose_name='نقطه مهم تصویر'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='mobile_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='mobile_jpeg',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='banners/generated/'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='mobile_webp',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='banners/generated/'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='mobile_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='render_signature',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(help_text='هر ابعادی مجاز است؛ پیشنهاد حداقل ۲۴۸۰ پیکسل عرض. نسخه\u200cی دسکتاپ و موبایل خودکار ساخته می\u200cشود.', upload_to='banners/source/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='فقط اگر می\u200cخواهی روی گوشی طرح کاملاً متفاوتی دیده شود. خالی بگذاری، نسخه\u200cی موبایل از همان تصویر اصلی ساخته می\u200cشود.', null=True, upload_to='banners/source/mobile/', verbose_name='تصویر مخصوص موبایل (اختیاری)'),
        ),
    ]
