# Generated by Django 5.0.6 on 2026-07-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='این نام (نه نام کاربری لاگین) زیر دیدگاه\u200cها و در سایت عمومی نمایش داده می\u200cشود. اگر خالی بماند، به\u200cجای آن یک نسخه\u200cی نقاب\u200cدار از نام کاربری نمایش داده می\u200cشود (مثلاً «moh***» به\u200cجای نام کاربری کامل) تا نام کاربری واقعی (که برای ورود استفاده می\u200cشود) در معرض دید عمومی قرار نگیرد.', max_length=50, verbose_name='نام نمایشی'),
        ),
    ]
