# Generated by Django 5.0.6 on 2026-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='مثلاً: تلگرام، اینستاگرام، توییتر (X)', max_length=50, verbose_name='نام شبکه اجتماعی')),
                ('icon', models.ImageField(upload_to='socials/', verbose_name='آیکون/لوگو')),
                ('url', models.URLField(verbose_name='لینک کانال/صفحه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order'],
            },
        ),
    ]
